# Generated by Django 4.1.6 on 2023-03-01 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_variants_variant_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='productphotos/')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='variants',
            old_name='variant_image1',
            new_name='variant_images',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='variant_category',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='variant_color',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='variant_gender',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='variant_image2',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='variant_image3',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='variant_name',
        ),
        migrations.AddField(
            model_name='products',
            name='product_category',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_gender',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], default='Men', max_length=10),
        ),
        migrations.AddField(
            model_name='variants',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='variants',
            name='variant_stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.AddField(
            model_name='image',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.products'),
        ),
        migrations.AddField(
            model_name='image',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.variants'),
        ),
        migrations.AddField(
            model_name='variants',
            name='variant_size',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='store.size'),
        ),
    ]
