# Generated by Django 4.1.6 on 2023-03-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_color_image_size_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.AddField(
            model_name='variants',
            name='variant_color',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
