# Generated by Django 4.1.6 on 2023-03-01 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_variants_variant_sport_products_product_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='variant_images',
        ),
    ]
