# Generated by Django 4.1.6 on 2023-03-03 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_variants_variant_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='variant',
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.products'),
        ),
    ]
