# Generated by Django 4.1.6 on 2023-03-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_variants_variant_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='variant_color',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='variant_price',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='variant_type',
        ),
        migrations.AddField(
            model_name='products',
            name='product_color',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='product_type',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
