# Generated by Django 4.1.6 on 2023-03-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_category_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(default=0, upload_to='Logos/'),
            preserve_default=False,
        ),
    ]
