# Generated by Django 4.1.6 on 2023-02-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_addresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='mobile',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='pincode',
            field=models.BigIntegerField(),
        ),
    ]
