# Generated by Django 4.1.6 on 2023-02-23 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_alter_account_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='profile_image',
        ),
    ]
