# Generated by Django 4.1.6 on 2023-02-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_remove_account_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
