# Generated by Django 4.1.6 on 2023-03-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_alter_account_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
