# Generated by Django 4.1.6 on 2023-03-08 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orders_cartitem_remove_orders_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='oder_total',
            new_name='order_total',
        ),
    ]
