# Generated by Django 4.1.6 on 2023-03-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_oder_total_orders_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default='D0A1C5F5', max_length=8),
        ),
    ]
