# Generated by Django 4.1.6 on 2023-03-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_orders_order_id_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default='6BDCCE72', max_length=8),
        ),
    ]
